export const GET_CURRENCY_PAIRS = 'GET_CURRENCY_PAIRS';
export const ADD_CURRENCY_PAIRS = 'ADD_CURRENCY_PAIRS';
export const UPDATE_CURRENCY_PAIRS = 'EDIT_CURRENCY_PAIRS';
export const DELETE_CURRENCY_PAIRS = 'DELETE_CURRENCY_PAIRS';
export const SAVE_OPTION_VALUE_FROM = 'SAVE_OPTION_VALUE_FROM';
export const SAVE_OPTION_VALUE_TO = 'SAVE_OPTION_VALUE_TO';
export const SAVE_OPTION_TIME_UPDATE = 'SAVE_OPTION_TIME_UPDATE';
